services:
  backend:
    build: /back
    ports:
      - '8081:8081'
    volumes:
      - ./back/src:/app/src
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "a"
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  front:
    build: /front
    ports:
      - '4200:4200'
    volumes:
      - /front/src:/app/front


