services:
  backend:
    build: /back
    ports:
      - '8080:8080'
    volumes:
      - ./back/src:/app/src
    depends_on:
      - dbpg
  dbpg:
    image: 'postgrest'
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
  front:
    build: /front
    ports:
      - '4200:4200'
    volumes:
      - /front/src:/app/front


