services:
  backend:
    build: /back
    ports:
      - '8080:8080'
    volumes:
      - ./back/src:/app/src
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=wildblog'
      - 'POSTGRES_PASSWORD=a'
  front:
    build: /front
    ports:
      - '4200:4200'
    volumes:
      - /front/src:/app/front
