services:
  backend:
    build: /back
    ports:
      - '8081:8080'
    volumes:
      - ./back/src:/app/src
    depends_on:
      - db
  db:
    image: 'mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  front:
    build: /front
    ports:
      - '4200:4200'
    volumes:
      - /front/src:/app/front


