services:
  backend:
    build: /back
    ports:
      - '8080:8080'
    volumes:
      - ./back/src:/app/src
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_DB=wildblogdatabase
      - POSTGRES_PASSWORD=@h9?3T6muS
      - POSTGRES_USER=wildadmin
    ports:
      - '5432:5432'
  front:
    build: /front
    ports:
      - '4200:4200'
    volumes:
      - /front/src:/app/front

